name: ocean_park
description: Ocean Park An Fish Ordering App

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # pay: ^1.0.1
  http: ^0.13.3
  get_it: ^7.0.0
  location: ^4.1.1
  provider: ^5.0.0
  upi_india: ^3.0.1
  image_picker: ^0.7.4
  firebase_core: ^1.1.0
  firebase_auth: ^1.1.2
  google_sign_in: ^5.0.2
  cloud_firestore: ^1.0.7
  firebase_storage: ^8.0.5
  shared_preferences: ^2.0.5



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
    - assets/images/login.png
    - assets/images/google.jpg
    - assets/images/photo.png
    
